### ISSUE TITLE
V4 API

### ISSUE THREAD

**Issue by morrislaptop** [asimlqt/php-google-spreadsheet-client#161]
Are you upgrading to this or do you recommend using Google's PHP SDK?

**Comment by asimlqt** [comment]
Good question, I've not really had a chance to look into it yet properly. I did have a quick look a while back and the (Official) Google API seems a lot easier to use now since it uses JSON and not XML.

It would mean a complete rewrite though so I need to decide whether there is a significant benefit to warrant a rewrite.

What are your thoughts?

**Comment by morrislaptop** [comment]
I'll have a look and post some sample code later

**Comment by morrislaptop** [comment]
tl;dr I'm not going to upgrade on existing projects but would use it for a new project. 

API is definitely not as nice as the extra features (e.g. inserting formulas, specifying ranges) make it more complicated. I think I would use the PHP SDK for my next project as it's one less dependency and I think I'd be able to wrap my head around the complexity.
