### ISSUE TITLE
Class DefaultServiceRequest not found.

### ISSUE THREAD

**Issue by luys** [asimlqt/php-google-spreadsheet-client#25]
Hi there,

I'm getting Class 'Google\Spreadsheet\DefaultServiceRequest' not found error message.
I'm using Yii framework and I've imported classes like this Yii::import('application.vendors.*');

**Comment by nhart** [comment]
I'm getting the same error

composer.json
{
    "require": {
        "google/apiclient": "1.0.*@beta",
        "asimlqt/php-google-spreadsheet-client": "2.3.*"
    }
}

<?php
use Google\Spreadsheet\DefaultServiceRequest;
use Google\Spreadsheet\ServiceRequestFactory;

$access_token = file_get_contents('access_token');

$serviceRequest = new DefaultServiceRequest($access_token);
ServiceRequestFactory::setInstance($serviceRequest);

apache error log
PHP Fatal error:  Class 'Google\\Spreadsheet\\DefaultServiceRequest' not found in

I've ran this 
composer dumpautoload

What am I doing wrong?

**Comment by jawanda** [comment]
@nhart Did you ever find a solution to this problem?  This is driving me nuts!

**Comment by nhart** [comment]
@jawanda  no, I ended up just exporting (as csv) my first sheet with the drive api.

**Comment by abhishekejam** [comment]
I found out the solution if anybody is still having this issue. Well, if you downloaded the package from github instead of installing via Composer then you are likely to encounter this issue.

Solution:
1. You need to download the attached directory if it doesn't exists and include in your "/path/to/google-api-php-client/vendor".
[asimlqt.zip](https://github.com/asimlqt/php-google-spreadsheet-client/files/1931160/asimlqt.zip)
2. You need to include the path to files as below:
require_once '/path/to/google-api-php-client/vendor/autoload.php';
require_once '/path/to/google-api-php-client/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/DefaultServiceRequest.php';
require_once '/path/to/google-api-php-client/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/ServiceRequestFactory.php';
require_once '/path/to/google-api-php-client/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/SpreadsheetService.php';
require_once '/path/to/google-api-php-client/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/SpreadsheetFeed.php';
require_once '/path/to/google-api-php-client/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/Spreadsheet.php';
require_once '/path/to/google-api-php-client/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/Util.php';
require_once '/path/to/google-api-php-client/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/Worksheet.php';
require_once '/path/to/google-api-php-client/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/WorksheetFeed.php';
require_once '/path/to/google-api-php-client/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/CellEntry.php';
require_once '/path/to/google-api-php-client/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/CellFeed.php';
require_once '/path/to/google-api-php-client/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/ListEntry.php';
require_once '/path/to/google-api-php-client/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/ListFeed.php';

That's it. Done
