### ISSUE TITLE
Replace CURL with Guzzle to allow for concurrent inserts

### ISSUE THREAD

**Issue by j0rd** [asimlqt/php-google-spreadsheet-client#44]
I'm using this library to create a fairly large spreadsheet multiple times a day (stock lists in a collection of ecommerce stores). Every hour, I'd like to do around 6000 rows.

Problem is right now $row->insert() requires a POST per insert. This makes it fairly slow. I've tried POSTing multiple entries in a POST to increase the throughput, but Google does not allow this.

From the docs, I can't find any other instance where bulk inserts are allowed either.

Because of this, I suggest perhaps using the Guzzle library to allow multiple concurrent inserts to happen at once.

Here's the docs for something like that:
http://docs.guzzlephp.org/en/latest/clients.html#sending-requests-with-a-pool

The API is also much friendlier to use that straight CURL. It does use CURL on the backend though.

If there's another way to send multiple inserts in a single POST than that would also work fine for me as well. Is this something which can get done with BatchRequest.php?

**Comment by asimlqt** [comment]
Thanks for the suggestion, I think Guzzle is the way forward. I'll implement it when i have some time available or you can implement it and send me a pull request.

As far as i can tell the api does not support batch inserts.

If you do decide to implement Guzzle please note the following points.

1. Implement ServiceRequestInterface, use DefaultServiceRequest as an example.
2. Add guzzle to composer.json
3. Update the docs to explain how to use guzzle. Don't change the default implementation of Curl because we want it to be backwards compatible.
4. write tests for the new implementation.

**Comment by asimlqt** [comment]
I would love t do this but I don't think it's going to be possible due to the way composer manages dependencies. It's not possible to have have 2 different versions of the same package running at the same time. Guzzle is a really popular library and will most likely be already used in most projects that use composer (we use it extensively at work).
